on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commit_spoofing_detective_job:
    runs-on: ubuntu-latest
    name: A job that checks for potentially spoofed commits
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Commit spoofing check
        id: commit-spoof
        uses: Ferejbo/commit-spoofing-detective-action@v1.1.1d
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Mismatch Output
        if: steps.commit-spoof.outputs.mismatch == 'true'
        run: echo "A commit spoofing was potentially detected."
